qiti: qiti::Profile Class Reference
qiti::Profile Class Reference
#include <qiti_Profile.hpp>
Classes
struct ScopedDisableProfiling
Static Public Member Functions
static void resetProfiling () noexcept
template<auto FuncPtr>
requires isFreeFunction<FuncPtr>
static QITI_API_INLINE void beginProfilingFunction () noexcept
template<auto FuncPtr>
requires isMemberFunction<FuncPtr>
static QITI_API_INLINE void beginProfilingFunction () noexcept
template<auto FuncPtr>
requires isFreeFunction<FuncPtr>
static QITI_API_INLINE void endProfilingFunction () noexcept
template<auto FuncPtr>
requires isMemberFunction<FuncPtr>
static QITI_API_INLINE void endProfilingFunction () noexcept
static void beginProfilingAllFunctions () noexcept
static void endProfilingAllFunctions () noexcept
template<auto FuncPtr>
requires isFreeFunction<FuncPtr>
static QITI_API_INLINE bool isProfilingFunction () noexcept
template<auto FuncPtr>
requires isMemberFunction<FuncPtr>
static QITI_API_INLINE bool isProfilingFunction () noexcept
template<typename Type >
static QITI_API_INLINE void beginProfilingType () noexcept
template<typename Type >
static QITI_API_INLINE void endProfilingType () noexcept
static uint64_t getNumHeapAllocationsOnCurrentThread () noexcept
static uint64_t getAmountHeapAllocatedOnCurrentThread () noexcept
template<auto FuncPtr>
requires isFreeFunction<FuncPtr> || isMemberFunction<FuncPtr>
static QITI_API_INLINE consteval const char * getFunctionName () noexcept
template<typename T >
static QITI_API_INLINE consteval const char * getTypeName () noexcept
Detailed Description
Utility class for runtime profiling of functions and types.
The Profile class provides a convenient interface for instrumenting and querying profiling data at runtime.
Definition at line 126 of file qiti_Profile.hpp.
Member Function Documentation
beginProfilingAllFunctions()
static void qiti::Profile::beginProfilingAllFunctions () static noexcept
beginProfilingFunction() [1/2]
template<auto FuncPtr> requires isFreeFunction<FuncPtr> static QITI_API_INLINE void qiti::Profile::beginProfilingFunction () inline static noexcept
Definition at line 145 of file qiti_Profile.hpp.
References beginProfilingFunction().
Referenced by beginProfilingFunction().
beginProfilingFunction() [2/2]
template<auto FuncPtr> requires isMemberFunction<FuncPtr> static QITI_API_INLINE void qiti::Profile::beginProfilingFunction () inline static noexcept
Definition at line 155 of file qiti_Profile.hpp.
References beginProfilingFunction().
beginProfilingType()
template<typename Type > static QITI_API_INLINE void qiti::Profile::beginProfilingType () inline static noexcept
Definition at line 205 of file qiti_Profile.hpp.
References beginProfilingType().
Referenced by beginProfilingType().
endProfilingAllFunctions()
static void qiti::Profile::endProfilingAllFunctions () static noexcept
endProfilingFunction() [1/2]
template<auto FuncPtr> requires isFreeFunction<FuncPtr> static QITI_API_INLINE void qiti::Profile::endProfilingFunction () inline static noexcept
Definition at line 165 of file qiti_Profile.hpp.
References endProfilingFunction().
Referenced by endProfilingFunction().
endProfilingFunction() [2/2]
template<auto FuncPtr> requires isMemberFunction<FuncPtr> static QITI_API_INLINE void qiti::Profile::endProfilingFunction () inline static noexcept
Definition at line 173 of file qiti_Profile.hpp.
References endProfilingFunction().
endProfilingType()
template<typename Type > static QITI_API_INLINE void qiti::Profile::endProfilingType () inline static noexcept
Definition at line 209 of file qiti_Profile.hpp.
References endProfilingType().
Referenced by endProfilingType().
getAmountHeapAllocatedOnCurrentThread()
static uint64_t qiti::Profile::getAmountHeapAllocatedOnCurrentThread () static noexcept
getFunctionName()
template<auto FuncPtr> requires isFreeFunction<FuncPtr> || isMemberFunction<FuncPtr> static QITI_API_INLINE consteval const char * qiti::Profile::getFunctionName () inline static noexcept
Definition at line 221 of file qiti_Profile.hpp.
getNumHeapAllocationsOnCurrentThread()
static uint64_t qiti::Profile::getNumHeapAllocationsOnCurrentThread () static noexcept
getTypeName()
template<typename T > static QITI_API_INLINE consteval const char * qiti::Profile::getTypeName () inline static noexcept
Get the compile-time demangled name of a type
Definition at line 228 of file qiti_Profile.hpp.
isProfilingFunction() [1/2]
template<auto FuncPtr> requires isFreeFunction<FuncPtr> static QITI_API_INLINE bool qiti::Profile::isProfilingFunction () inline static noexcept
Returns
true if we are currently profling function.
Definition at line 187 of file qiti_Profile.hpp.
References isProfilingFunction().
Referenced by isProfilingFunction().
isProfilingFunction() [2/2]
template<auto FuncPtr> requires isMemberFunction<FuncPtr> static QITI_API_INLINE bool qiti::Profile::isProfilingFunction () inline static noexcept
Returns
true if we are currently profling function. Member function overload.
Definition at line 198 of file qiti_Profile.hpp.
References isProfilingFunction().
resetProfiling()
static void qiti::Profile::resetProfiling () static noexcept
The documentation for this class was generated from the following file:
source/qiti_Profile.hpp