name: Build Qiti

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mac-build-xcode:
    if: false # temporarily disable to save money
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Configure CMake (Xcode generator)
        run: cmake . -B build -G Xcode

      - name: Build
        run: cmake --build build --config Debug --target qiti_tests
        
      - name: Run Unit Tests
        run: |
          cd build
          ctest -C Debug

  mac-build-clang-ninja:
    if: false # temporarily disable to save money
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install LLVM 16 & Ninja
        run: |
          brew install llvm@16 ninja
          echo "PATH=$(brew --prefix llvm@16)/bin:$PATH" >> $GITHUB_ENV

      - name: Configure CMake (Ninja, LLVM Clang)
        run: cmake . -B build \
             -G Ninja \
             -DCMAKE_BUILD_TYPE=Debug \
             -DCMAKE_C_COMPILER=clang \
             -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build --target qiti_tests
        
      - name: Run Unit Tests
        run: |
          cd build
          ctest -C Debug
          
  linux-build-clang-ninja:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install LLVM 16 & Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-16 ninja-build
          echo "CC=clang-16" >> $GITHUB_ENV
          echo "CXX=clang++-16" >> $GITHUB_ENV

      - name: Configure CMake (Ninja, LLVM Clang)
        run: |
          cmake . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=clang-16 \
            -DCMAKE_CXX_COMPILER=clang++-16
             
      - name: Dump link line
        run: |
          ls
          ninja -C build -v qiti_tests

#      - name: Build
#        run: cmake --build build --target qiti_tests
#
#      - name: Run Unit Tests
#        run: |
#          cd build
#          ctest -C Debug

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install cpplint
        run: pip3 install cpplint

      - name: Run CPPLint
        run: ./runCpplint.sh
