
name: Build Qiti

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-xcode:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Configure CMake (Xcode generator)
        run: cmake . -B build -G Xcode

      - name: Build
        run: cmake --build build --config Debug --target qiti_tests

  build-clang-ninja:
    runs-on: macos-15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install LLVM 16 & Ninja
        run: |
          brew install llvm@16 ninja
          echo "PATH=$(brew --prefix llvm@16)/bin:$PATH" >> $GITHUB_ENV

      - name: Configure CMake (Ninja, LLVM Clang)
        run: cmake . -B build \
             -G Ninja \
             -DCMAKE_BUILD_TYPE=Debug \
             -DCMAKE_C_COMPILER=clang \
             -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build --target qiti_tests
